### ISSUE TITLE
Plugin should not output file to `compilation.options.output.path` if filename is absolute path

### ISSUE THREAD

**Issue by BjornMelgaard** [danethurber/webpack-manifest-plugin#108]
Plugin should not output file to [`compilation.options.output.path`](https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L157) if filename is absolute path

[HtmlWebpackPlugin has this feature](https://github.com/jantimon/html-webpack-plugin/blob/0cf580c628a495d77b85e35ed1b9d244e2ec5ae0/index.js#L40-L43)

**Comment by mastilver** [comment]
And it does not, it was fixed on 1.3.2
