### ISSUE TITLE
Output manifest json file in different directory

### ISSUE THREAD

**Issue by bcdbuddy** [danethurber/webpack-manifest-plugin#115]
As suggested I would like to output the manifest json file in different directory which is not the publicPath where the built files are!

Thank you kindly!

**Comment by ningollan** [comment]
👍

**Comment by mastilver** [comment]
Just do `fileName: path.resolve(__dirname, './the/manifest/path.json')`

**Comment by bcdbuddy** [comment]
Great ! Thanks 👍😊
