### ISSUE TITLE
Can I get hash string of each file after build time?

### ISSUE THREAD

**Issue by hmtri1011** [danethurber/webpack-manifest-plugin#116]
After build time this is what I got on manifest.json file
`{
       app.js": "app-3cb7bb73.bundle.js"
       ....
  }`

Can I get manifest.json file that contains hash string??
something like:

`{
      'app-3cb7bb73.bundle.js': '3cb7bb73xxxxxxxxxxxxxx'
  }` 

Thanks

**Comment by mastilver** [comment]
yes, just use one of the hooks: https://github.com/danethurber/webpack-manifest-plugin#hooks-options
