### ISSUE TITLE
Allow content serialization to be modified

### ISSUE THREAD

**Issue by tylerbwilliams** [danethurber/webpack-manifest-plugin#122]
Currently, the content returned from the `generate` function is then passed to `JSON.stringify`.  We don't get the chance to use a different serialization model.

My use case is that I want to create a `manifest.properties` file instead of a `manifest.json` file.  I can write my own `generate` function to create the output as a valid properties file, but then `JSON.stringify` wraps it in quotes and escapes all my newlines.

Can we have a `serialize` option that defaults to `JSON.stringify`, for those who want their own strategy for this?

**Comment by mastilver** [comment]
Can you send a PR please?

**Comment by mastilver** [comment]
done in https://github.com/danethurber/webpack-manifest-plugin/pull/123
