### ISSUE TITLE
is it possible to generate the manifest to a file in conjunction with webpack dev server?

### ISSUE THREAD

**Issue by kellyrmilligan** [danethurber/webpack-manifest-plugin#143]
I thought maybe 
```
new ManifestPlugin({
          fileName: 'webpack-client-assets.json',
          writeToFileEmit: true
        }),
```

would do it, but not dice. using with `webpack-dev-server` pinned at 3.0.0,  and 

2.0.0-rc.2 of the plugin.

**Comment by kellyrmilligan** [comment]
tried downgrading to latest 1.x of this puglin, and still no dice.

**Comment by mastilver** [comment]
I do not get your issue... Are saying `writeToFileEmit` doesn't work?

**Comment by kellyrmilligan** [comment]
Yes. I’m trying to get the file generated on disk as well. ATM it’s only in memory

**Comment by mastilver** [comment]
Are you talking about the manifest? Or JS, CSS?

**Comment by kellyrmilligan** [comment]
Sorry yes the manifest.json, I’m doing a universal setup and want the manifest file always to be on disk so the server can pick it up.

**Comment by mastilver** [comment]
Hum... weird we have a test to cover that... https://github.com/danethurber/webpack-manifest-plugin/blob/24acf95aaaaa4a2050e5f62340b66b2d0f6932aa/spec/plugin.integration.spec.js#L354

Can you try to create a failing test or create a repository to reproduce the issue?

**Comment by kellyrmilligan** [comment]
I guess I’m wondering is Memoery-fs what webpack dev server uses? I’m seeing the issue when using that. I’ll push up my current repo as it’s an example app still and update this with it.

**Comment by kellyrmilligan** [comment]
ok, so,  this is my bad. I was creating a new project with all the latest stuff for the most part, then realized for this I was using `webpack-dev-server@^3` with webpack 3. with webpack dev server 2 this is working as expected. sorry about this!

**Comment by roborourke** [comment]
I'm having the same issue, is this meant to support `webpack-dev-server` v3?

**Comment by shadowc** [comment]
I have this exact same issue... Are you implying this plugin does NOT support `webpack-dev-server: 3.11.0` ?

**Comment by shadowc** [comment]
Downgrading to webpack-dev-server v2 isn't an option, it doesn't work in webpack 5.1...

**Comment by shellscape** [comment]
@shadowc please use the Edit feature on replies. Posting repeated replies generates unneeded noise. If you're having trouble with webpack-dev-server, check out https://github.com/shellscape/webpack-plugin-serve. It's a lot lighter
