### ISSUE TITLE
Scope hoisting webpack 4

### ISSUE THREAD

**Issue by bugzpodder** [danethurber/webpack-manifest-plugin#151]
https://github.com/facebook/create-react-app/issues/4492
https://github.com/facebook/create-react-app/pull/4077#issuecomment-389270627

- [concatenateModules](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L214) option is on by default in production
- import in [SvgComponent](https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/fixtures/kitchensink/src/features/webpack/SvgComponent.js) produces [ConcatenatedModule](https://github.com/webpack/webpack/blob/master/lib/optimize/ConcatenatedModule.js#L254) (rather than a [NormalModule](https://github.com/webpack/webpack/blob/master/lib/NormalModule.js)).
- ConcatenatedModule doesn't have userRequest field for  [webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L45), which crashes.

**Comment by petetnt** [comment]
Related? https://github.com/danethurber/webpack-manifest-plugin/pull/117

**Comment by bugzpodder** [comment]
Yes, looks like the same issue.
