### ISSUE TITLE
Default fileName clash with PWA manifest.json

### ISSUE THREAD

**Issue by pxwee5** [danethurber/webpack-manifest-plugin#160]
Just realised that the default fileName setting is `manifest.json`, which clashes with the manifest.json used by PWA applications. 

I know we can change it using the fileName property, but should we change the default to something else? `assets.json` perhaps?

**Comment by toastal** [comment]
https://developer.mozilla.org/en-US/docs/Web/Manifest#Deploying_a_manifest_with_the_link_tag

It should be a `*.webmanifest` instead of `*.json` anyhow. :upside_down_face:
