### ISSUE TITLE
chunk-manifest-webpack-plugin?

### ISSUE THREAD

**Issue by mateatslc** [danethurber/webpack-manifest-plugin#2]
How this plugin differs from https://github.com/diurnalist/chunk-manifest-webpack-plugin?

**Comment by okonet** [comment]
They have completely different purposes. 

This one can be used to get a filename from a entry-point name, so when you add [hash] or [chunkhash] to your filenames, you can reference these files on your html page.

The chunk-manifest-webpack-plugin does a different thing:

> maps chunk ids to their resulting asset files. Webpack can then read this mapping, assuming it is provided somehow on the client, instead of storing a mapping (with chunk asset hashes) in the bootstrap script, which allows to actually leverage long-term caching.

When used, webpack will not update the hash of the common chunk (if nothing else changed in it) so you cache buster not being destroyed.

See https://github.com/diurnalist/chunk-manifest-webpack-plugin/issues/1 and http://clarkdave.net/2015/01/how-to-use-webpack-with-rails/#including-precompiled-assets-in-views

**Comment by danethurber** [comment]
@okonet thanks for the clarification. closing this
