### ISSUE TITLE
Removing old files when compiling

### ISSUE THREAD

**Issue by rasmuswoelk** [danethurber/webpack-manifest-plugin#20]
Hi

I'm using your plugin for versioning on my site but after a lot of saves I get a lot of cached files in my build-folder, which goes to github.

I'm kinda new to webpack but I was hoping there is some solution that deletes all files in the folder when it generates new hashed-files. Is is possible in some way?

Thanks!

**Comment by danethurber** [comment]
personally i use this https://github.com/johnagan/clean-webpack-plugin but there might be other options. hope it helps

**Comment by rasmuswoelk** [comment]
Thanks!

**Comment by benjaminadrom** [comment]
@danethurber but doesnt this remove the whole folder? doesnt make this the whole "chunkhash blabla" in the filename obsolete?
So the browser has to load ALL again? Am i wrong?
