### ISSUE TITLE
The plugin does not work

### ISSUE THREAD

**Issue by davidmoseler** [danethurber/webpack-manifest-plugin#204]
In webpack.config.js, I put

var ManifestPlugin = require('webpack-manifest-plugin');
...
module.exports = (env,args) => {
    return {
    ...
    plugins: [
        ...
        new ManifestPlugin({
            fileName: './webpack-manifest.json'
        })
    ]

After running webpack, build succeeds as usual, but no webpack-manifest.json file is produced. There is no error message produced and no documentation on how to debug. No solution for this problem is found online.

I'm happy to provide more information if required. In principle, I would like to know what to do to debug a plugin which simply does nothing.

**Comment by mariosanchez** [comment]
What was your problem? Did you fix it?
