### ISSUE TITLE
An option for outputing fullpath of files as key 

### ISSUE THREAD

**Issue by mohsen1** [danethurber/webpack-manifest-plugin#23]
It would output this 

```
{"entry": "entry-abcd1234"}
```

instead of this

```
{"/path/to/entry": "entry-abcd1234"}
```

with that option

**Comment by monochrome-yeh** [comment]
I have the same issue,
I think of the solution that should provide such as `[name]`, `[path]` , etc..,
and then we could solve this requirement.

**Comment by calvinwyoung** [comment]
+1 for this

**Comment by mastilver** [comment]
@mohsen1 @monochrome-yeh @calvinwyoung @kilokeith @igor-im @dmzkrsk @Bnaya I'm not sure to understand what you want. Can any of you provide a simple webpack config with the actual and expected output?

**Comment by mastilver** [comment]
I'm closing this as it't now possible using the `map` option:
https://github.com/danethurber/webpack-manifest-plugin/blob/master/spec/plugin.spec.js#L545-L566
