### ISSUE TITLE
Generated manifest has some missing items

### ISSUE THREAD

**Issue by posix4e** [danethurber/webpack-manifest-plugin#34]
Lighthouse failed on the following 
- Manifest contains name    The name property identifies your app and is required. Learn more.
- Manifest contains background_color    When your app launches from a user's homescreen, the browser uses background_color to paint the background of the browser while your app loads for a smooth transition experience. Learn more.
- Manifest contains theme_color   
- Manifest contains icons at least 192px

**Comment by thasmo** [comment]
I think this webpack plugin is not related to web-app manifests. It's purpose is to generate an asset manifest which maps hashed filenames to original file-names.
