### ISSUE TITLE
Cannot GET /manifest.json

### ISSUE THREAD

**Issue by Khachatour** [danethurber/webpack-manifest-plugin#39]
Hey there folks!
I saw a problem today when I am using these plugin I am getting error
Which says: 
`Cannot GET /manifest.json`
Any suggestions ?

**Comment by a-x-** [comment]
// I'm not a maintainer.

It's not the `webpack-manifest-plugin` problem.
Check you server and webpack publicPath settings

You should not want to GET manifest.json. Instead of manifest usually used on the server.
