### ISSUE TITLE
Do not add code splitting bundles into manifest

### ISSUE THREAD

**Issue by a-x-** [danethurber/webpack-manifest-plugin#46]
I want to use `require.ensure` for separating some large modules as DLL.
But `webpack-manifest-plugin` add it into manifest 
so chunks are loading immediately

**Comment by gmac** [comment]
There are many cases for knowing _all_ built files that came out of webpack, so it seems to me that this should be made an option allowing non-initial chunk reports to be turned off.

**Comment by a-x-** [comment]
yep, I agree,
me PR was optional initially

Can you name the flag?
I proposed this one: `omitDll: true`

**Comment by gmac** [comment]
That's certainly succinct. More verbose but possibly more obvious would be `omitNonInitialChunks` or `omitNonEntryChunks`

**Comment by mastilver** [comment]
I *personally* prefer to reduce the number of options we add (the reason I closed #43 ), and have this:
```
filter: ({chunk, file}) => {
  return chunk.isInitial();
}
``` 

But if you think that should be added then fine ;)

**Comment by a-x-** [comment]
in other words, do you propose to make this behaviour default in next major version and recommend to use [chunk-manifest-webpack-plugin](https://github.com/soundcloud/chunk-manifest-webpack-plugin) for chunks handling?

correct me, please

**Comment by mastilver** [comment]
Yes make it default and use filter to filter out unneeded ones
