### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by mastilver** [danethurber/webpack-manifest-plugin#49]
@danethurber just added me as a collaborators to this project

I think it will be better if I'm not the only one making the decisions on this project! :)

So if you are ready to spend some time maintaining this project, ping me here

ping @jordansexton @gmac @andreicek @tikotzky @martynovs @nickescallon @modosc  @iliakan @a-x- @davidmpaz @Lobstrosity @weaverryan @craigmichaelmartin @wtgtybhertgeghgtwtg @orbiteleven

**Comment by wtgtybhertgeghgtwtg** [comment]
I have a few ideas that could help, sure, but how did my name come up?  I don't think I've ever touched this project.
Did you confuse my name for somebody else's?  Happens all the time.

**Comment by craigmichaelmartin** [comment]
https://github.com/danethurber/webpack-manifest-plugin/pull/32

**Comment by mastilver** [comment]
@wtgtybhertgeghgtwtg I pinged everybody who contributed / opened a PR

**Comment by zuzusik** [comment]
I can definitely spend some time reviewing PRs, but as I am not an expert in how `WebPack` works under the hood this would be mostly general logic checking/analyzing + code style reviews

**Comment by a-x-** [comment]
+1, Me too
Let's try

**Comment by mastilver** [comment]
I'm quite familiar with `webpack`, not that much with the history of `webpack-manifest-plugin`
So I guess with the three of us we have a good mixed team ;)

I will ask Dane to add you as Collaborator, the only rule is don't push to `master` changes impacting the plugin's logic

**Comment by mastilver** [comment]
I'm closing this now, but feel free to reach out here if you are willing to help ;)

**Comment by gmac** [comment]
I don't mind helping out

**Comment by mastilver** [comment]
@gmac definitely, I think you can help on 2 and 3 of #51

**Comment by mastilver** [comment]
@gmac @a-x- @zuzusik I created a slack channel here: https://webpack.slack.com/messages/C6CCZ0DSS

Anyone else welcome of course ;)

**Comment by a-x-** [comment]
Can you create an invite to invntrm@gmail.com?

**Comment by mastilver** [comment]
I asked @d3viant0ne to add all of you and @danethurber on slack

**Comment by mastilver** [comment]
Alright, so I'm created a gitter instead: https://gitter.im/webpack-manifest-plugin#
