### ISSUE TITLE
Custom values

### ISSUE THREAD

**Issue by hooloovooo** [danethurber/webpack-manifest-plugin#5]
Would it be possible to add custom attributes to the manifest file. It's used to add GCM keys among other stuff to enable Push notifications to browsers.

**Comment by danethurber** [comment]
can you provide an example? This might be something that is out of the scope of this package

**Comment by hooloovooo** [comment]
I've just come to the conclusion that this seems to be for cache manifest. I was looking for something to handle app manifest. I'll look into writing it myself. :)
