### ISSUE TITLE
Improve tests coverage

### ISSUE THREAD

**Issue by mastilver** [danethurber/webpack-manifest-plugin#51]
Those are not covered by tests:
- [x] https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L34-L37 (#59)
- [x] https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L52-L54
- [x] https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L58 (#59)
- [x] https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L68-L70 (#59)
- [x] https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L108-L113 (#56)

**Comment by a-x-** [comment]
I'm starting look at #L34-L37

**Comment by mastilver** [comment]
I'm working on L52-L54
WIP: https://github.com/danethurber/webpack-manifest-plugin/tree/test-update-hot
