### ISSUE TITLE
Add reduce, initValue, map, filter options

### ISSUE THREAD

**Issue by mastilver** [danethurber/webpack-manifest-plugin#55]
- [x] filter (#66)
- [x] map
- [x] reduce
- [x] seed (#57)

-----

fix: #48 
```js
filter: ({chunk, file}) => {
  return chunk.isInitial();
}
```

fix: #25 

```js
initValue: {

} // will be used as the initValue for reduce, default to `{}`
```

fix #35 

```js
map: ({chunk, file}) => {
  return {
    file,
    hash: chunk.source.integrity
  };
}
```

```js
reduce: (manifest, {chunk, file}) => {
  return manifest;
}
```

-----
`map` and `reduce` can't be used at the same time

**Comment by nathanbirrell** [comment]
Hey @mastilver I've added the initValue on my fork. Created PR https://github.com/danethurber/webpack-manifest-plugin/pull/57

**Comment by mastilver** [comment]
@a-x- @zuzusik @gmac Once unit tests are close to 💯  I would like to start working on that
After re-thinking it I'm not sure if `reduce` is necessary; `map` and `filter` will probably be enough 

Thoughts?

**Comment by weaverryan** [comment]
Just dropping a note that this would also solve #37, where we want to be able to tweak (prefix) both the keys and values of the manifest. This would be a much more flexible way of handling it than the one-off option I proposed there.

**Comment by a-x-** [comment]
`initValue` name is too abstract as I see.
