### ISSUE TITLE
Option to map entries or normalize paths on both Windows and OSX/Linux

### ISSUE THREAD

**Issue by mikegleasonjr** [danethurber/webpack-manifest-plugin#60]
Hi,

The keys of the manifest on Windows are: `"path\\file.ext"`

Whereas on Linux/OSX it is: `"path/file.ext"`

Making it difficult to reference a resource by its key in the manifest.

Can we have a callback function to transform the manifest elements prior to insertion or have both paths use slashes (`/`)?

**Comment by mastilver** [comment]
> Can we have a callback function to transform the manifest elements prior to insertion or have both paths use slashes (/)?

This is what I'm planning to do on #55

**Comment by weaverryan** [comment]
+1 - this is the 1 other hack that we're maintaining in our [fork](https://github.com/symfony/webpack-encore/blob/master/lib/webpack/webpack-manifest-plugin.js#L48-L54). I really like #55 ;)

**Comment by a-x-** [comment]
I have two points:
* as i understand, it should be default behaviour
* how to solve different platforms problem: when building goes no the, say, Windows, and running on the linux.

**Comment by mastilver** [comment]
@a-x- you are making a good point here

We should stick to the linux path even on windows so it's consistent if you relly on the key during your build process

**Comment by weaverryan** [comment]
Yep, our hack is exactly to make sure that the keys are always the same, regardless of platform. +1 for it being the default behavior.

**Comment by mastilver** [comment]
@mikegleasonjr @weaverryan Would you mind giving me an example of webpack.config.js where this issue occurs, that will help me writing the tests (as I don't have access to a windows machine...)

**Comment by mastilver** [comment]
ping @mikegleasonjr @weaverryan

**Comment by mikegleasonjr** [comment]
@mastilver https://github.com/danethurber/webpack-manifest-plugin#usage

**Comment by mastilver** [comment]
@mikegleasonjr  Good point ;)

```
{
  context: __dirname,
  entry: {
    'test\\one': './fixtures/file.js',
    two: './fixtures/file-two.js'
  },
  plugins: [
    new ManifestPlugin()
  ]
}

```

**Comment by mikegleasonjr** [comment]
Thanks @mastilver !
