### ISSUE TITLE
Is it possible to prevent the manifest from being written to disk?

### ISSUE THREAD

**Issue by philipwalton** [danethurber/webpack-manifest-plugin#86]
I'm managing the manifest in-memory and through my own module, so I'd like the option to *not* write it to disk in some cases.

I assumed that returning `null` or `undefined` from the reduce function or filtering out all the assets would prevent writing to disk, but that doesn't seem to happen.

Is this supported?

**Comment by mastilver** [comment]
if you are using `memory-fs`, it shouldn't write to disk

**Comment by mastilver** [comment]
> I'm managing the manifest in-memory 

I checked your boilerplate, to check how you are doing that. You might be interested by: https://github.com/danethurber/webpack-manifest-plugin/pull/76

Anyway, I don't think an option we want
