### ISSUE TITLE
Add `compress` option

### ISSUE THREAD

**Issue by evilebottnawi** [danethurber/webpack-manifest-plugin#96]
To avoid spaces and newlines

**Comment by mastilver** [comment]
Hi @evilebottnawi 

Can you tell me what the issue with spaces and newlines?

**Comment by evilebottnawi** [comment]
@mastilver less bytes - faster file system read on server side

**Comment by mastilver** [comment]
Sorry, I won't be implementing that

The gain would be almost not noticeable so not really worth adding yet another options

**Comment by mastilver** [comment]
But if you feels something else on plugin is not performant, feel free to submit a PR as I'm sure you will find a few perf issues ;)
